### ISSUE TITLE
API

### ISSUE THREAD

**Issue by allangrds** [allangrds/Express-JWT-Simple-API#1]
# Tasks
- Necessita estar autenticado
- [ ] GET /tasks 200 | 401
  - [ ] pagination
  - [ ] filter by title or description
- [ ] GET /tasks/{id} 200 | 404 | 401
- [ ] POST /tasks 201 | 400 | 401
  - [ ] Title
    - [ ] Required
    - [ ] Max: 30
  - [ ] Description
    - [ ] Required
    - [ ] Max: 255
- [ ] PATCH /tasks/{id} 202 | 400 | 404 | 401
  - [ ] Title
    - [ ] Required
    - [ ] Max: 30
  - [ ] Description
    - [ ] Required
    - [ ] Max: 255
- [ ] DELETE /tasks/{id} 204 |  404 | 401
  
# Auth
- [ ] POST /auth/login 200 | 400 | 401
  - [ ] email
    - [ ] Required
    - [ ] Max: 30
  - [ ] password
    - [ ] Required
    - [ ] Max: 30

- [ ] POST /auth/logout 200 | 401
  - [ ] token
    - [ ] Required

- [ ] POST /auth/refresh 200 | 401
  - [ ] token
    - [ ] Required
    
# Outros
- [ ] GET /user 200 | 401
- [ ] POST /users 200 | 401
     
obs: colocar rate limit em todas as rotas

**Comment by lucianopf** [comment]
Dps da pra forkar e criar um novo endpoint pra cada recurso com a rota tipo `/${resource}/watch` que abre um Websocket e daí pra cada novo recurso criado ele notifica o consumidor em tempo real 🤔 😬 🤓
